name: konglog
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^2.0.0
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

